# Generated by Django 2.0.7 on 2018-07-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='BDapp.Project'),
        ),
    ]
